//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliverX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historia
    {
        public int id_Historia { get; set; }
        public int id_Przesyłka { get; set; }
        public int id_Status { get; set; }
        public System.DateTime Data_zmiany_statusu { get; set; }
        public string Opis { get; set; }
    
        public virtual Przesyłka Przesyłka { get; set; }
        public virtual Status Status { get; set; }
    }
}
