//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliverX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kurs()
        {
            this.Przesyłka = new HashSet<Przesyłka>();
        }
    
        public int id_Kurs { get; set; }
        public int id_Pracownik { get; set; }
        public int id_Pojazd { get; set; }
        public System.DateTime Data { get; set; }
        public double Liczba_kilometrów { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Pojazd Pojazd { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Przesyłka> Przesyłka { get; set; }
    }
}
