//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliverX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeliverXEntities : DbContext
    {
        public DeliverXEntities()
            : base("name=DeliverXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Firma_Ubezpieczeniowa> Firma_Ubezpieczeniowa { get; set; }
        public virtual DbSet<Historia> Historia { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<Kurs> Kurs { get; set; }
        public virtual DbSet<Pojazd> Pojazd { get; set; }
        public virtual DbSet<Pracownik> Pracownik { get; set; }
        public virtual DbSet<Przesyłka> Przesyłka { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Typ_Płatności> Typ_Płatności { get; set; }
        public virtual DbSet<Typ_Pojazdu> Typ_Pojazdu { get; set; }
        public virtual DbSet<Typ_Przesyłki> Typ_Przesyłki { get; set; }
        public virtual DbSet<Typ_Ubezpieczenia> Typ_Ubezpieczenia { get; set; }
        public virtual DbSet<Ubezpieczenie> Ubezpieczenie { get; set; }
        public virtual DbSet<Uprawnienie> Uprawnienie { get; set; }
        public virtual DbSet<Historia_widok> Historia_widok { get; set; }
        public virtual DbSet<Pojazd_widok> Pojazd_widok { get; set; }
        public virtual DbSet<Przesyłka_widok> Przesyłka_widok { get; set; }
        public virtual DbSet<Ubezpieczenie_widok> Ubezpieczenie_widok { get; set; }
        public virtual DbSet<Uprawnienie_widok> Uprawnienie_widok { get; set; }
    }
}
