//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliverX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pojazd_widok
    {
        public int id_Pojazd { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Nr_rejestracyjny { get; set; }
        public string Typ_pojazdu { get; set; }
        public double Max_ładowność { get; set; }
        public string Jednostka_ładowności { get; set; }
        public System.DateTime Rocznik { get; set; }
        public double Stan_licznika { get; set; }
        public string Jednostka_licznika { get; set; }
        public System.DateTime Stan_licznika_na_dzień { get; set; }
        public string Rodzaj_paliwa { get; set; }
    }
}
