//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliverX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pracownik()
        {
            this.Kurs = new HashSet<Kurs>();
            this.Uprawnienie = new HashSet<Uprawnienie>();
        }
    
        public int id_Pracownik { get; set; }
        public string Imię { get; set; }
        public string Nazwisko { get; set; }
        public string PESEL { get; set; }
        public System.DateTime Data_urodzenia { get; set; }
        public System.DateTime Data_zatrudnienia { get; set; }
        public string Państwo { get; set; }
        public string Miasto { get; set; }
        public string Kod_pocztowy { get; set; }
        public string Ulica { get; set; }
        public string Nr_domu_mieszkania { get; set; }
        public string Nr_telefonu { get; set; }
        public string Adres_e_mail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kurs> Kurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uprawnienie> Uprawnienie { get; set; }
    }
}
