//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliverX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przesyłka_widok
    {
        public int id_Przesyłka { get; set; }
        public string Typ_Przesyłki { get; set; }
        public string Odbiorca_Imię { get; set; }
        public string Odbiorca_Nazwisko { get; set; }
        public string Nadawca_Imię { get; set; }
        public string Nadawca_Nazwisko { get; set; }
        public string Do_miasta { get; set; }
        public string Na_ulicę { get; set; }
        public string Do_mieszkania { get; set; }
        public string Pracownik_Imię { get; set; }
        public string Pracownik_Nazwisko { get; set; }
        public System.DateTime Data_nadania { get; set; }
        public System.DateTime Data_wymaganego_dostarczenia { get; set; }
        public Nullable<System.DateTime> Data_rzeczywistego_dostarczenia { get; set; }
        public double Waga { get; set; }
        public string Jednostka_wagi { get; set; }
        public decimal Opłata { get; set; }
        public string Waluta { get; set; }
        public string Nr_dokumentu_przewozowego { get; set; }
        public string Typ_płatności { get; set; }
    }
}
