//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliverX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przesyłka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Przesyłka()
        {
            this.Historia = new HashSet<Historia>();
        }
    
        public int id_Przesyłka { get; set; }
        public int id_Typ_Przesyłki { get; set; }
        public int id_Doręczenia { get; set; }
        public int id_Nadawca { get; set; }
        public int id_Odbiorca { get; set; }
        public int id_Kurs { get; set; }
        public System.DateTime Data_nadania { get; set; }
        public System.DateTime Data_wymaganego_dostarczenia { get; set; }
        public Nullable<System.DateTime> Data_rzeczywistego_dostarczenia { get; set; }
        public double Waga { get; set; }
        public string Jednostka_wagi { get; set; }
        public decimal Opłata { get; set; }
        public string Waluta { get; set; }
        public string Nr_dokumentu_przewozowego { get; set; }
        public int id_Typ_Płatności { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historia> Historia { get; set; }
        public virtual Klient Klient { get; set; }
        public virtual Klient Klient1 { get; set; }
        public virtual Klient Klient2 { get; set; }
        public virtual Kurs Kurs { get; set; }
        public virtual Typ_Płatności Typ_Płatności { get; set; }
        public virtual Typ_Przesyłki Typ_Przesyłki { get; set; }
    }
}
