//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliverX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubezpieczenie_widok
    {
        public int id_Ubezpieczenie { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Typ_pojazdu { get; set; }
        public string Nr_rejestracyjny { get; set; }
        public string Typ_Ubezpieczenia { get; set; }
        public string Firma { get; set; }
        public string Nr_polisy { get; set; }
        public System.DateTime Obowiązuje_od { get; set; }
        public System.DateTime Obowiązuje_do { get; set; }
        public decimal Cena { get; set; }
        public string Waluta { get; set; }
    }
}
