//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliverX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uprawnienie_widok
    {
        public int id_Uprawnienia { get; set; }
        public string Imię { get; set; }
        public string Nazwisko { get; set; }
        public string Typ_pojazdu { get; set; }
        public string Nr_dokumentu { get; set; }
    }
}
